xterm -hold -e .//run_all_d0.sh &
xterm -hold -e .//run_all_d1.sh &
xterm -hold -e .//run_all_d2.sh &
xterm -hold -e .//run_all_d3.sh &
xterm -hold -e .//run_all_d4.sh &
xterm -hold -e .//run_all_d5.sh &
xterm -hold -e .//run_all_d6.sh &
xterm -hold -e .//run_all_d7.sh &
xterm -hold -e .//run_all_d8.sh &
xterm -hold -e .//run_all_d9.sh &
xterm -hold -e .//run_all_d10.sh &
xterm -hold -e .//run_all_d11.sh &
xterm -hold -e .//run_all_d12.sh &
xterm -hold -e .//run_all_d13.sh &
xterm -hold -e .//run_all_d14.sh &
xterm -hold -e .//run_all_d15.sh &
xterm -hold -e .//run_all_d16.sh &
xterm -hold -e .//run_all_d17.sh &
xterm -hold -e .//run_all_d18.sh &
xterm -hold -e .//run_all_d19.sh &
xterm -hold -e .//run_all_d20.sh &
xterm -hold -e .//run_all_d21.sh &
xterm -hold -e .//run_all_d22.sh &
xterm -hold -e .//run_all_d23.sh &
xterm -hold -e .//run_all_d24.sh &
xterm -hold -e .//run_all_d25.sh &
xterm -hold -e .//run_all_d26.sh &
xterm -hold -e .//run_all_d27.sh &
xterm -hold -e .//run_all_d28.sh &
xterm -hold -e .//run_all_d29.sh &
xterm -hold -e .//run_all_d30.sh &
xterm -hold -e .//run_all_d31.sh &
xterm -hold -e .//run_all_d32.sh &
xterm -hold -e .//run_all_d33.sh &
xterm -hold -e .//run_all_d34.sh &
xterm -hold -e .//run_all_d35.sh &
xterm -hold -e .//run_all_d36.sh &
xterm -hold -e .//run_all_d37.sh &
xterm -hold -e .//run_all_d38.sh &
xterm -hold -e .//run_all_d39.sh &
xterm -hold -e .//run_all_d40.sh &
xterm -hold -e .//run_all_d41.sh &
xterm -hold -e .//run_all_d42.sh &
xterm -hold -e .//run_all_d43.sh &
xterm -hold -e .//run_all_d44.sh &
xterm -hold -e .//run_all_d45.sh &
xterm -hold -e .//run_all_d46.sh &
xterm -hold -e .//run_all_d47.sh &
xterm -hold -e .//run_all_d48.sh &
xterm -hold -e .//run_all_d49.sh &
